
import skShenanigans from './images/skshenanigans.jpg';
import Stanley from './images/stanley.png'
import flipkingx from './images/flipkingx.png'
import ms from './images/msBits.png'
import tat from './images/tatming cover.jpg'
import secretFur from './images/secret furnishing.png'
import wysd2023 from './images/wysd2023.png'
import alex1 from './images/alex1.png'
import farmojt from './images/farmojt.png'
import UPSAsia from './images/UPSAsia.png'
import gotchuHome from './images/gotchuHome.png'
import gotchuWater from './images/gotchuWater.png' 
import yeelightPro from './images/yeelightPro.png'
import TNBTEpoxy from './images/TNBTEpoxy.png'
import TNBTAlvyn from './images/TNBTAlvyn.png'
import TNBTThai from './images/TNBTThai.png'
import TNBTTaiwan from './images/TNBTTaiwan.png'
import TNBTFishSoap from './images/TNBTFishSoap.png'
import bayo from './images/bayo.png'
import hisalters from './images/his alters.png'
import handum from './images/handum.png'
import frontliners from './images/frontliners.png'
import coconut from './images/coconut.png'
import vaccine from './images/vaccine.png'
import igtuble from './images/igtuble.png'
import wysd2022 from './images/wysd2022.png'
import whyisatu from './images/whyisatu.png'
import wins from './images/wins.png'
import sibucauan from './images/sibucauan.png'
import buenavista from './images/buenavista.png'
import dagyawPro from './images/dagyaw provincial.png'
import dagyawbasa from './images/dagyaw basa.png'
import pushups100 from './images/100pushups.png'
import sexedu from './images/sexeducation.png'
import indianfood from './images/indianfood.png'
import mothersday from './images/mothersday.png'
import colors from './images/colors.png'
import grains from './images/grains.png'
import bully from './images/bully.png'
import btsbiot from './images/btsbiot.png'
import contentcreator from './images/contentcreation.png'
import plasticbot from './images/plasticbottle.png'
import grabfinal from './images/grabfinal.png'
import ifoundthe1 from './images/ifoundthe1.png'


 const Data = [
    {name: "SK Shenanigans",
        playlist: "vlogs",
        link:"https://www.youtube.com/embed/2Dmes5jeGd4?si=KLlX3yB6LcTpd_SN",
        img: skShenanigans,
        format: "horizontal",
        software: "premiere pro",
        market: "national",
        latest: false,
    },
    {name: "Stanley",
      playlist: "clients",
      link:"https://www.youtube.com/embed/cDtruaQeTqg?si=_bpqZSByc1Ijj6gj",
      img: Stanley,
      format: "horizontal",
      software: "premiere pro",
      market: "international",
      latest: true,
    },
    {name: "FlipKingX",
      playlist: "clients",
      link:"https://youtube.com/embed/TvAgjPUi1kQ",
      img: flipkingx,
      format: "vertical",
      software: "premiere pro",
      market: "international",
      latest: false,
    },
    {name: "MS Bits and Bytes",
      playlist: "clients",
      link:"https://youtube.com/embed/OuJdUfk2w0M?feature=share",
      img: ms,
      format: "vertical",
      software: "premiere pro",
      market: "international",
      latest: false,
    },
    {name: "Tat Ming",
      playlist: "clients",
      link:"https://www.youtube.com/embed/kmN9o-bN4RI?si=8mvSRXbbYyzBTrVl" ,
      img: tat,
      format: "vertical",
      software: "premiere pro",
      market: "international",
      latest: false,
    },
    {name: "Secret Furnishing",
      playlist: "clients",
      link:"https://www.youtube.com/embed/iwaFyoc3DXU?si=Xztt_ZcFl0mTt7Rm" ,
      img: secretFur,
      format: "vertical",
      software: "premiere pro",
      market: "international",
      latest: false,
    },
    {name: "WYSD Contest Entry",
      playlist: "clients",
      link:"https://www.youtube.com/embed/1d49eRskbdk?si=fOydXa1Hz0KfKnCz" ,
      img: wysd2023,
      format: "vertical",
      software: "premiere pro",
      market: "international",
      latest: false,
    },
    {name: "Salary in CV",
      playlist: "clients",
      link:"https://www.youtube.com/embed/-tj6QE24vg0?si=3WCXW3ykMWN8kLZE",
      img: alex1,
      format: "vertical",
      software: "premiere pro",
      market: "international",
      latest: false,
    },
    {name: "Farm Practice OJT",
      playlist: "clients",
      link:"https://www.youtube.com/embed/iDfZC2BBm9w?si=1dpJmqc5PmFqrFwB",
      img: farmojt,
      format: "horizontal",
      software: "premiere pro",
      market: "local",
      latest: false,
    },
    {name: "UPS PowerUPSAsia",
      playlist: "clients",
      link:"https://www.youtube.com/embed/lBBvFHH3E3k?si=3AAet8q2VQxGxsn2",
      img: UPSAsia,
      format: "vertical",
      software: "premiere pro",
      market: "international",
      latest: false,
    },
    {name: "IT Show Water Purifiers",
      playlist: "clients",
      link:"https://www.youtube.com/embed/60MhfGA7dBk?si=nk4StOl3d56ZeaEg",
      img: gotchuWater,
      format: "horizonatal",
      software: "premiere pro",
      market: "international",
      latest: false,
    },
    {name: "IT Show Home Products",
      playlist: "clients",
      link:"https://www.youtube.com/embed/jQulwV3DjLU?si=jlrl4O5kTyjPttXb",
      img: gotchuHome,
      format: "horizontal",
      software: "premiere pro",
      market: "international",
      latest: false,
    },
    {name: "Yeelight Pro Gateway",
    playlist: "clients",
    link:"https://www.youtube.com/embed/iTACpHYzbkE?si=fM8j1OhNGY1kJ874" ,
    img: yeelightPro,
    format: "horizontal",
    software: "premiere pro",
    market: "international",
    latest: false,
    },
    {name: "Alvyn's Animal Cards",
    playlist: "clients",
    link:"https://www.youtube.com/embed/Khhfk-ut8U0?si=BfObYFW_Fubx3FBH" ,
    img: TNBTAlvyn,
    format: "vertical",
    software: "premiere pro",
    market: "international",
    latest: false,
    },
    {name: "Kaitlyn's Epoxy Crafts",
    playlist: "clients",
    link:"https://www.youtube.com/embed/zIl9a7xXoZk?si=MbCuI6bxntr7uc2f" ,
    img: TNBTEpoxy,
    format: "vertical",
    software: "premiere pro",
    market: "international",
    latest: false,
    },
    {name: "Thai Sleep Temperature Project",
    playlist: "clients",
    link:"https://www.youtube.com/embed/P6AdHarr3iM?si=8DJaVdLsMKB_aBH_",
    img: TNBTThai,
    format: "vertical",
    software: "premiere pro",
    market: "international",
    latest: false,
    },
    {name: "Taiwan Baby Seat Sensor",
    playlist: "clients",
    link:"https://www.youtube.com/embed/nqNCEXMwIPE?si=Q4fzQZaw63nW9nsP" ,
    img: TNBTTaiwan ,
    format: "vertical",
    software: "premiere pro",
    market: "international",
    latest: false,
    },
    {name: "Fish Bone Soap",
    playlist: "clients",
    link:"https://www.youtube.com/embed/vjYdJ8_jlKU?si=qxyGmHLyTKdTjLv0",
    img: TNBTFishSoap ,
    format: "vertical",
    software: "premiere pro",
    market: "international",
    latest: false,
    },
    {name: "Bayo | Dress",/////////////////////////
    playlist: "films",
    link:"https://www.youtube.com/embed/vo9b-XnFH60?si=ElB5y35O0s645SWr",
    img: bayo,
    format: "horizontal",
    software: "premiere pro",
    market: "local",
    latest: false,
    },
    {name: "Handum | Dream",
    playlist: "films",
    link:"https://www.youtube.com/embed/iQYdDe6x_yc?si=ys61zoNWCHHbywsx" ,
    img: handum,
    format: "horizontal",
    software: "premiere pro",
    market: "local",
    latest: false,
    },
    {name: "His Alters",
    playlist: "films",
    link:"https://www.youtube.com/embed/sxJ6yf_sNDg?si=zNKhAmHZFaGph5jC",
    img: hisalters,
    format: "horizontal",
    software: "premiere pro",
    market: "local",
    latest: false,
    },
    {name: "Frontlines",
    playlist: "films",
    link:"https://www.youtube.com/embed/iHeyJ8JcrV4?si=EFSzqs4X0sCjG2cm",
    img: frontliners,
    format: "horizontal",
    software: "premiere pro",
    market: "local",
    latest: false,
    },
    {name: "Coconut | Jim",
    playlist: "films",
    link:"https://www.youtube.com/embed/gHmaOY_VKDs?si=T8lBoGwKAlU36azV" ,
    img: coconut,
    format: "horizontal",
    software: "premiere pro",
    market: "local",
    latest: false,
    },
    {name: "Vaccine | KD",
    playlist: "films",
    link:"https://www.youtube.com/embed/Sc4i4r1eZk8?si=GUmWfLDYR1IO74PI" ,
    img: vaccine,
    format: "horizontal",
    software: "premiere pro",
    market: "local",
    latest: false,
    },
    {name: "Igtuble | Elly and Rodney",
    playlist: "films",
    link:"https://www.youtube.com/embed/ZCG6j-DXVzE?si=l1B4zo2TkXEsU7dq" ,
    img: igtuble,
    format: "horizontal",
    software: "premiere pro",
    market: "local",
    latest: false,
    },
    {name: "World Youth Skills Day 2022",
    playlist: "films",
    link:"https://www.youtube.com/embed/ZCG6j-DXVzE?si=l1B4zo2TkXEsU7dq" ,
    img: wysd2022,
    format: "horizontal",
    software: "premiere pro",
    market: "local",
    latest: false,
    },
    {name: "Why ISAT U?",
    playlist: "vlog",
    link:"https://www.youtube.com/embed/oUrTrBsLr4s?si=yfC06UC0YfuvVOMG",
    img: whyisatu,
    format: "horizontal",
    software: "premiere pro",
    market: "local",
    latest: false,
    },
    {name: "WASH In Schools",
    playlist: "clients",
    link:"https://www.youtube.com/embed/lFs5G9MtxZQ?si=La2vz46FKis5iG7I",
    img: wins,
    format: "horizontal",
    software: "kinemaster",
    market: "national",
    latest: false,
    },
    {name: "Town Festival Teaser for Sibucauan ES",
    playlist: "clients",
    link:"https://www.youtube.com/embed/9sX79WHhj9s?si=Tnas7r-_5L3ynWi_" ,
    img: sibucauan,
    format: "horizontal",
    software: "kinemaster",
    market: "local",
    latest: false,
    },
    {name: "Town Festival Buenavista ES",
    playlist: "clients",
    link:"https://www.youtube.com/embed/JuMbSlbx9-s?si=Es9RXFMkotdV2Kr_" ,
    img: buenavista,
    format: "horizontal",
    software: "kinemaster",
    market: "local",
    latest: false,
    },
    {name: "DAGYAW Provincial Contest Entry",
    playlist: "clients",
    link:"https://www.youtube.com/embed/CDxvP_bMRFU?si=GEf8ez3hsMGcnwOk",
    img: dagyawPro,
    format: "horizontal",
    software: "kinemaster",
    market: "local",
    latest: false,
    },
    {name: "Dagyaw Basa",
    playlist: "vlogs",
    link:"https://www.youtube.com/embed/CDxvP_bMRFU?si=hCVeuIxMj97yXv02" ,
    img: dagyawbasa,
    format: "horizontal",
    software: "Premiere Pro",
    market: "local",
    latest: false,
    },
    {name: "100 Push Up Challenge",
    playlist: "vlogs",
    link:"https://www.youtube.com/embed/lbQKDsQXvz0?si=nbV9xB3AbZ-EISJj",
    img: pushups100,
    format: "horizontal",
    software: "kinemaster",
    market: "international",
    latest: false,
    },
    {name: "Sex Education",
    playlist: "vlogs",
    link:"https://www.youtube.com/embed/AW5hpwwTsbc?si=0EOmi4gqW7UMNVl3" ,
    img: sexedu,
    format: "square",
    software: "kinemaster",
    market: "international",
    latest: false,
    },
    {name: "Indian Food Dirty of Not?",
    playlist: "vlogs",
    link:"https://www.youtube.com/embed/YMSJ_iv3jBI?si=Wxo6unbr2vrJerTo",
    img: indianfood,
    format: "square",
    software: "premiere pro",
    market: "international",
    latest: false,
    },
    {name: "Mother's Day 2022",
    playlist: "vlogs",
    link:"https://www.youtube.com/embed/wpDRO46moXs?si=CNrbygCGSafHk7CL" ,
    img: mothersday,
    format: "horizontal",
    software: "premiere pro",
    market: "international",
    latest: false,
    },
    {name: "Colors",
    playlist: "clients",
    link:"https://www.youtube.com/embed/z1afoi6TtLE?si=acTw2bCnKF4BrGAo",
    img: colors,
    format: "horizontal",
    software: "kinemaster",
    market: "international",
    latest: false,
    },
    {name: "Diversity / Grains",
    playlist: "vlogs",
    link:"https://www.youtube.com/embed/kHZsw3Z_VVY?si=N9OErWX8vmUX0F-n" ,
    img: grains,
    format: "square",
    software: "kinemaster",
    market: "international",
    latest: false,
    },
    {name: "Bully",
    playlist: "vlogs",
    link:"https://www.youtube.com/embed/PAUrqnMGC4g?si=T-AqdtpjkfEUnTzB" ,
    img: bully,
    format: "square",
    software: "kinemaster",
    market: "international",
    latest: false,
    },
    {name: "BTS Biot",
    playlist: "vlogs",
    link:"https://www.youtube.com/embed/yhDDXUgYhKg?si=uszLLE5CcWUyTqXU" ,
    img: btsbiot,
    format: "square",
    software: "kinemaster",
    market: "international",
    latest: false,
    },  
    {name: "What is content creation?",
    playlist: "vlogs",
    link:"https://www.youtube.com/embed/kFaSaDVYccQ?si=dwQaAdFPPYMNFgBj" ,
    img: contentcreator,
    format: "horizontal",
    software: "kinemaster",
    market: "international",
    latest: false,
    },  
    {name: "Bottled Water",
    playlist: "vlogs",
    link:"https://www.youtube.com/embed/r34MY3Qk7Tg?si=zZwOCROpm-ci_JMc",
    img: plasticbot,
    format: "square",
    software: "kinemaster",
    market: "international",
    latest: false,
    },  
    {name: "Grab X Nas Academy Final Output",
    playlist: "vlogs",
    link:"https://www.youtube.com/embed/09qz6N_FBMM?si=jkYHhXRGI18HU3wL" ,
    img: grabfinal,
    format: "square",
    software: "kinemaster",
    market: "international",
    latest: false,
    }, 
    {name: "Finally I Found the One",
    playlist: "vlogs",
    link:"https://www.youtube.com/embed/qWTpC1Zy1qg?si=0Qwycg4E4XNdWQxO" ,
    img: ifoundthe1,
    format: "horizontal",
    software: "kinemaster",
    market: "international",
    latest: false,
    }, 




]
export default Data