
import skShenanigans from './images/skshenanigans.jpg';
import Stanley from './images/stanley.png'
import flipkingx from './images/flipkingx.png'
import ms from './images/msBits.png'
import tat from './images/tatming cover.jpg'
import secretFur from './images/secret furnishing.png'
import wysd2023 from './images/wysd2023.png'
import alex1 from './images/alex1.png'
import farmojt from './images/farmojt.png'
import UPSAsia from './images/UPSAsia.png'
import gotchuHome from './images/gotchuHome.png'
import gotchuWater from './images/gotchuWater.png' 
import yeelightPro from './images/yeelightPro.png'
import TNBTEpoxy from './images/TNBTEpoxy.png'
import TNBTAlvyn from './images/TNBTAlvyn.png'
import TNBTThai from './images/TNBTThai.png'
import TNBTTaiwan from './images/TNBTTaiwan.png'
import TNBTFishSoap from './images/TNBTFishSoap.png'

 const Data = [
    {name: "SK Shenanigans",
        playlist: "vlogs",
        link:"https://www.youtube.com/embed/2Dmes5jeGd4?si=KLlX3yB6LcTpd_SN",
        img: skShenanigans,
        format: "horizontal",
        latest: false,
    },
    {name: "Stanley",
      playlist: "clients",
      link:"https://www.youtube.com/embed/cDtruaQeTqg?si=_bpqZSByc1Ijj6gj",
      img: Stanley,
      format: "horizontal",
      latest: true,
    },
    {name: "FlipKingX",
      playlist: "clients",
      link:"https://youtube.com/embed/TvAgjPUi1kQ",
      img: flipkingx,
      format: "vertical",
      latest: false,
    },
    {name: "MS Bits and Bytes",
      playlist: "films",
      link:"https://youtube.com/embed/OuJdUfk2w0M?feature=share",
      img: ms,
      format: "vertical",
      latest: false,
    },
    {name: "Tat Ming",
      playlist: "clients",
      link:"https://www.youtube.com/embed/kmN9o-bN4RI?si=8mvSRXbbYyzBTrVl" ,
      img: tat,
      format: "vertical",
      latest: false,
    },
    {name: "Secret Furnishing",
      playlist: "clients",
      link:"https://www.youtube.com/embed/iwaFyoc3DXU?si=Xztt_ZcFl0mTt7Rm" ,
      img: secretFur,
      format: "vertical",
      latest: false,
    },
    {name: "WYSD Contest Entry",
      playlist: "clients",
      link:"https://www.youtube.com/embed/1d49eRskbdk?si=fOydXa1Hz0KfKnCz" ,
      img: wysd2023,
      format: "vertical",
      latest: false,
    },
    {name: "Salary in CV",
      playlist: "clients",
      link:"https://www.youtube.com/embed/-tj6QE24vg0?si=3WCXW3ykMWN8kLZE",
      img: alex1,
      format: "vertical",
      latest: false,
    },
    {name: "Farm Practice OJT",
      playlist: "clients",
      link:"https://www.youtube.com/embed/iDfZC2BBm9w?si=1dpJmqc5PmFqrFwB",
      img: farmojt,
      format: "horizontal",
      latest: false,
    },
    {name: "UPS PowerUPSAsia",
      playlist: "clients",
      link:"https://www.youtube.com/embed/lBBvFHH3E3k?si=3AAet8q2VQxGxsn2",
      img: UPSAsia,
      format: "vertical",
      latest: false,
    },
    {name: "IT Show Water Purifiers",
      playlist: "clients",
      link:"https://www.youtube.com/embed/60MhfGA7dBk?si=nk4StOl3d56ZeaEg",
      img: gotchuWater,
      format: "horizonatal",
      latest: false,
    },
    {name: "IT Show Home Products",
      playlist: "clients",
      link:"https://www.youtube.com/embed/jQulwV3DjLU?si=jlrl4O5kTyjPttXb",
      img: gotchuHome,
      format: "horizontal",
      latest: false,
    },
    {name: "Yeelight Pro Gateway",
    playlist: "clients",
    link:"https://www.youtube.com/embed/iTACpHYzbkE?si=fM8j1OhNGY1kJ874" ,
    img: yeelightPro,
    format: "horizontal",
    latest: false,
    },
    {name: "Alvyn's Animal Cards",
    playlist: "clients",
    link:"https://www.youtube.com/embed/Khhfk-ut8U0?si=BfObYFW_Fubx3FBH" ,
    img: TNBTAlvyn,
    format: "vertical",
    latest: false,
    },
    {name: "Kaitlyn's Epoxy Crafts",
    playlist: "clients",
    link:"https://www.youtube.com/embed/zIl9a7xXoZk?si=MbCuI6bxntr7uc2f" ,
    img: TNBTEpoxy,
    format: "vertical",
    latest: false,
    },
    {name: "Thai Sleep Temperature Project",
    playlist: "clients",
    link:"https://www.youtube.com/embed/P6AdHarr3iM?si=8DJaVdLsMKB_aBH_",
    img: TNBTThai,
    format: "vertical",
    latest: false,
    },
    {name: "Taiwan Baby Seat Sensor",
    playlist: "clients",
    link:"https://www.youtube.com/embed/nqNCEXMwIPE?si=Q4fzQZaw63nW9nsP" ,
    img: TNBTTaiwan ,
    format: "vertical",
    latest: false,
    },
    {name: "Fish Bone Soap",
    playlist: "clients",
    link:"https://www.youtube.com/embed/vjYdJ8_jlKU?si=qxyGmHLyTKdTjLv0",
    img: TNBTFishSoap ,
    format: "vertical",
    latest: false,
    },

]
export default Data